name: Create Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4.1.1

      # Step 2: Log in to Docker Hub (if pushing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag module04:${{ github.sha }}

      # Step 4 (Optional): Push the Docker image to a registry
      - name: Push the Docker image
        run: |
          docker tag module04:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/module04:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/module04:${{ github.sha }}
